# Generated by Django 5.2.1 on 2026-09-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='txn_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
